[ubuntu_user*]
    auth users = ubuntu_user*
    uid = ubuntu_user*
    gid = ubuntu_user*
    path = /home/folder*
    comment = home folder
    read only = no
    list = no
    hosts allow = *
    secrets file = /etc/rsyncd.scrt
    strict modes = false
