# uwsgi config file
[uwsgi]
plugin = python3

# change into the root project directory
chdir = /home/django_proj*

# virtual environment for our project
virtualenv = /opt/venv/djangoEnv

# interface with Django project by importing
# the application callable from the wsgi.py
# file in Django project directory
module = django_proj*.wsgi:application

master = true
processes = 5
uid = django_proj*
gid = www-data

# monitor python modules mtime to trigger reload
# use only in development
py-autoreload = 1

# how uWSGI should listen for connections
# SOCKET MUST MATCH:
# /etc/nginx/sites-available/folder*
socket = /run/uwsgi/django_proj*.sock

# modify the ownership and permissions of the
# socket because we will be giving the web server
# write access
chown-socket = ubuntu_user*:www-data
chmod-socket = 660

# socket file will be automatically cleaned up
# when the service is stopped
vacuum = true

logto = /opt/logs/folder*/uwsgi.log
